# Generated by Django 3.1.2 on 2020-10-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('myapp', '0003_auto_20201021_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
